// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vldkjcpbxrzppudgrrvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZGtqY3BieHJ6cHB1ZGdycnZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIwNDcxNjYsImV4cCI6MjA5NzYyMzE2Nn0.AkZ4WaFO5Wn0fyuRpg3YP7FKXsgLdaXS8Uaj0-7z9k4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});